export const SUBMIT_EVENT = "SUBMIT_EVENT";
export const SUBMIT_EVENT_ERROR = "SUBMIT_EVENT_ERROR";
export const RESET_SUBMIT_EVENT_STATUS = "RESET_SUBMIT_EVENT_STATUS";
export const DELETE_EVENT = "DELETE_EVENT";